### ISSUE TITLE
[Roadmap] Season 2023-2024

### ISSUE THREAD

**Issue by Nouw** [Nouw/smoelenboek#21]
# Roadmap Season 2023-2024

Hello everyone,

As this project continues to grow and evolve, having a roadmap is essential ensuring that we're all moving in the same direction. This issue lays out the planned features, improvements, and milestones for the current season.

## Critical (Must-Have)
- [ ] Proper role management #22

## High (Should-Have)
- [ ] Improved error handling #23 
- [ ] Extend documentation

## Medium (Could-Have)
- [x] Forms and Activities #24
- [x] CI/CD for compiling and deploying #25
- [ ] Face detection on photos #4

## Low (Nice-to-Have)
- [ ] Solver for practice timetables

This roadmap isn't set in stone. If any features become more important and/or are not listed, please share.
