### ISSUE TITLE
Implement Activity Registration within Smoelenboek

### ISSUE THREAD

**Issue by Nouw** [Nouw/smoelenboek#24]
To streamline the process for our members, it would be beneficial to centralize all activity registrations within Smoelenboek. Not only would this provide a unified experience, but it would also allow us to pre-fill forms with user information, simplifying the registration process.

## Tasks:
- [x] **Activities Landing Page**:
- Develop a dedicated landing page for activities. This will serve as a hub where users can view available activities and initiate the registration process.
- Note: While the long-term goal is to make this page accessible to anonymous users, this can be implemented in a later phase.
- [x] **Form Creation**: Design and develop intuitive forms for activity registration. These forms should be versatile enough to cater to the needs of various activities.
- [x] **Integrate forms into Activities**: Ensure that the relevant forms are linked to their corresponding activities. This might require dynamic form selection based on the activity type or requirements.
- [x] **Link Users with Forms**: Implement a feature where members' information can be automatically inserted into forms during the registration process, leveraging the data already available within Smoelenboek.

**Comment by Nouw** [comment]
Maybe add the sumup api for checking out, but will need to create our own SDK for this.

**Comment by Nouw** [comment]
Currently we are quite far regarding the activities and the forms, there are still a couple of tasks left (see list below). The plan is to finish these before the end of Q1 (March 31th). Which personally speaking seems feasible, keeping in mind the other tasks related to this.

- [ ] Translation
- [ ] Anonymous user registration
- [ ] Images / Covers for the activity
- [ ] Activity list in dashboard
- [ ] Activity updating in dashboard
- [ ] Link the responses to a google sheet
- [ ] Notifications (nice to have)

**Comment by Dwarf-Nebula** [comment]
- [ ] Automatically add privacy/data usage question.

**Comment by Nouw** [comment]
Currently there are the following tasks left:

- [ ] Removing registration user side
- [ ] Removing registration admin side
- [ ] See specific response in dashboard

**Comment by Nouw** [comment]
Only thing left is fixing the translation and some eslint errors, will probably deploy a release next week.
